import pytest

pytest.importorskip("torch")


def test_public_imports_work_from_package_root():
    import vit_from_scratch as vit

    expected = {
        "ViTConfig",
        "CIFAR10_CLASSES",
        "CIFAR10_MEAN",
        "CIFAR10_STD",
        "DataLoaders",
        "build_transforms",
        "limit_dataset",
        "build_dataloaders",
        "PatchEmbedding",
        "MultiHeadSelfAttention",
        "MLP",
        "TransformerEncoderBlock",
        "VisionTransformer",
        "LearnedPositionEmbedding",
        "CosinePositionEmbedding",
        "build_rope_cache",
        "apply_rope",
        "set_seed",
        "get_device",
        "move_batch_to_device",
        "accuracy",
        "train_one_epoch",
        "evaluate",
        "train",
        "classification",
        "mae",
        "dino",
        "build_classification_model",
        "classification_loss",
        "classification_train_step",
        "classification_eval_step",
        "MaskedAutoencoder",
        "patchify",
        "random_patch_mask",
        "masked_reconstruction_loss",
        "mae_train_step",
        "mae_eval_step",
        "dino_loss",
        "update_teacher_ema",
        "dino_train_step",
        "unnormalize_image",
        "make_patch_grid",
        "plot_training_curves",
        "plot_predictions",
        "plot_class_attention",
    }

    missing = {name for name in expected if not hasattr(vit, name)}
    assert not missing, f"Missing public exports at package root: {sorted(missing)}"


def test_no_sys_path_hacks_needed_for_public_imports():
    import vit_from_scratch as vit

    expected = (
        "ViTConfig",
        "CIFAR10_CLASSES",
        "CIFAR10_MEAN",
        "CIFAR10_STD",
        "DataLoaders",
        "build_transforms",
        "limit_dataset",
        "build_dataloaders",
        "PatchEmbedding",
        "MultiHeadSelfAttention",
        "MLP",
        "TransformerEncoderBlock",
        "VisionTransformer",
        "LearnedPositionEmbedding",
        "CosinePositionEmbedding",
        "build_rope_cache",
        "apply_rope",
        "set_seed",
        "get_device",
        "move_batch_to_device",
        "accuracy",
        "train_one_epoch",
        "evaluate",
        "train",
        "classification",
        "mae",
        "dino",
        "build_classification_model",
        "classification_loss",
        "classification_train_step",
        "classification_eval_step",
        "MaskedAutoencoder",
        "patchify",
        "random_patch_mask",
        "masked_reconstruction_loss",
        "mae_train_step",
        "mae_eval_step",
        "dino_loss",
        "update_teacher_ema",
        "dino_train_step",
        "unnormalize_image",
        "make_patch_grid",
        "plot_training_curves",
        "plot_predictions",
        "plot_class_attention",
    )
    for name in expected:
        assert getattr(vit, name, None) is not None


@pytest.mark.parametrize(
    ("module_name", "attribute_name"),
    [
        ("vit_from_scratch", "ViTConfig"),
        ("vit_from_scratch", "CIFAR10_CLASSES"),
        ("vit_from_scratch", "CIFAR10_MEAN"),
        ("vit_from_scratch", "CIFAR10_STD"),
        ("vit_from_scratch", "DataLoaders"),
        ("vit_from_scratch", "build_transforms"),
        ("vit_from_scratch", "limit_dataset"),
        ("vit_from_scratch", "build_dataloaders"),
        ("vit_from_scratch", "PatchEmbedding"),
        ("vit_from_scratch", "MultiHeadSelfAttention"),
        ("vit_from_scratch", "MLP"),
        ("vit_from_scratch", "TransformerEncoderBlock"),
        ("vit_from_scratch", "VisionTransformer"),
        ("vit_from_scratch", "LearnedPositionEmbedding"),
        ("vit_from_scratch", "CosinePositionEmbedding"),
        ("vit_from_scratch", "build_rope_cache"),
        ("vit_from_scratch", "apply_rope"),
        ("vit_from_scratch", "set_seed"),
        ("vit_from_scratch", "get_device"),
        ("vit_from_scratch", "move_batch_to_device"),
        ("vit_from_scratch", "accuracy"),
        ("vit_from_scratch", "train_one_epoch"),
        ("vit_from_scratch", "evaluate"),
        ("vit_from_scratch", "train"),
        ("vit_from_scratch", "classification"),
        ("vit_from_scratch", "mae"),
        ("vit_from_scratch", "dino"),
        ("vit_from_scratch", "build_classification_model"),
        ("vit_from_scratch", "classification_loss"),
        ("vit_from_scratch", "classification_train_step"),
        ("vit_from_scratch", "classification_eval_step"),
        ("vit_from_scratch", "MaskedAutoencoder"),
        ("vit_from_scratch", "patchify"),
        ("vit_from_scratch", "random_patch_mask"),
        ("vit_from_scratch", "masked_reconstruction_loss"),
        ("vit_from_scratch", "mae_train_step"),
        ("vit_from_scratch", "mae_eval_step"),
        ("vit_from_scratch", "dino_loss"),
        ("vit_from_scratch", "update_teacher_ema"),
        ("vit_from_scratch", "dino_train_step"),
        ("vit_from_scratch", "unnormalize_image"),
        ("vit_from_scratch", "make_patch_grid"),
        ("vit_from_scratch", "plot_training_curves"),
        ("vit_from_scratch", "plot_predictions"),
        ("vit_from_scratch", "plot_class_attention"),
    ],
)
def test_public_api_is_importable(module_name, attribute_name):
    module = __import__(module_name, fromlist=[attribute_name])
    assert getattr(module, attribute_name) is not None
